/* ============================================
   MENU DATA - REI GROUP
   ============================================ */

// Coffee Bar Menu Data
const coffeeMenuData = {
  categories: [
    {
      id: "hot-beverages",
      name: "Hot Beverages",
      image: "../assets/hot-beverages.jpeg",
    },
    { id: "tea", name: "Tea", image: "../assets/tea.jpeg" },
    {
      id: "cold-drinks",
      name: "Cold Drinks",
      image: "../assets/cold-drinks.jpeg",
    },
    { id: "add-on", name: "Add-On" },
    { id: "shakes", name: "Shakes", image: "../assets/shakes.jpeg" },
    {
      id: "refreshers",
      name: "Refreshers",
      image: "../assets/refreshers.jpeg",
    },
    {
      id: "fruit-smoothies",
      name: "Fruit Smoothies",
      image: "../assets/fruit-smoothies.jpeg",
    },
    {
      id: "spirits-glass",
      name: "Spirits (Glass)",
      image: "../assets/spirits-glass.jpeg",
    },
    {
      id: "spirits-bottles",
      name: "Spirits (Bottles)",
      image: "../assets/spirits-bottles.jpeg",
    },
    {
      id: "fresh-juices",
      name: "Fresh Juices",
      image: "../assets/fresh-juices.jpeg",
    },
    {
      id: "croissants",
      name: "Croissants",
      image: "../assets/croissants.jpeg",
    },
    { id: "desserts", name: "Desserts", image: "../assets/desserts.jpeg" },
  ],
  items: [
    // HOT BEVERAGES
    { id: "espresso", name: "Espresso", price: 2.0, category: "hot-beverages" },
    {
      id: "double-espresso",
      name: "Double Espresso",
      price: 3.5,
      category: "hot-beverages",
    },
    {
      id: "espresso-decaf",
      name: "Espresso Decaf",
      price: 2.0,
      category: "hot-beverages",
    },
    {
      id: "americano",
      name: "Americano",
      price: 4.0,
      category: "hot-beverages",
    },
    {
      id: "macchiato",
      name: "Macchiato",
      price: 3.5,
      category: "hot-beverages",
    },
    {
      id: "affogato-caramel",
      name: "Affogato Caramel",
      price: 4.0,
      category: "hot-beverages",
    },
    {
      id: "cappuccino",
      name: "Cappuccino",
      price: 5.0,
      category: "hot-beverages",
    },
    {
      id: "cafe-latte",
      name: "Cafe Latte",
      price: 5.0,
      category: "hot-beverages",
    },
    {
      id: "cafe-mocha",
      name: "Cafe Mocha",
      price: 5.0,
      category: "hot-beverages",
    },
    {
      id: "caramel-macchiato",
      name: "Caramel Macchiato",
      price: 5.0,
      category: "hot-beverages",
    },
    {
      id: "latte-brulee",
      name: "Latte Brûlée",
      price: 5.0,
      category: "hot-beverages",
    },
    {
      id: "hot-chocolate",
      name: "Hot Chocolate",
      price: 5.0,
      category: "hot-beverages",
    },
    {
      id: "flavored-tea",
      name: "Flavored Tea",
      price: 3.0,
      category: "hot-beverages",
    },
    {
      id: "matcha-latte",
      name: "Matcha Latte",
      price: 5.5,
      category: "hot-beverages",
    },
    {
      id: "lebanese-coffee",
      name: "Lebanese Coffee",
      price: 3.0,
      category: "hot-beverages",
    },

    // TEA (Each type separately)
    {
      id: "jasmine-phoenix-eyes",
      name: "Jasmine Phoenix Eyes",
      price: 3.5,
      category: "tea",
    },
    {
      id: "strawberry-green-tea",
      name: "Strawberry Green Tea",
      price: 3.5,
      category: "tea",
    },
    {
      id: "yellow-mountain-tea",
      name: "Yellow Mountain Tea",
      price: 3.5,
      category: "tea",
    },
    { id: "puer-tea", name: "Pu'er Tea", price: 3.5, category: "tea" },
    { id: "hibiscus", name: "Hibiscus", price: 3.5, category: "tea" },
    { id: "blue-pea-tea", name: "Blue Pea Tea", price: 3.5, category: "tea" },
    {
      id: "rose-petal-flowers",
      name: "Rose Petal Flowers",
      price: 3.5,
      category: "tea",
    },
    { id: "lotus-flower", name: "Lotus Flower", price: 3.5, category: "tea" },
    { id: "royal-tea-pot", name: "Royal Tea Pot", price: 7.0, category: "tea" },
    {
      id: "flower-bloom-pot-normal",
      name: "Flower Bloom Pot (Normal)",
      price: 7.0,
      category: "tea",
    },
    {
      id: "flower-bloom-pot-blue",
      name: "Flower Bloom Pot (Blue)",
      price: 7.0,
      category: "tea",
    },
    {
      id: "flower-bloom-pot-purple",
      name: "Flower Bloom Pot (Purple)",
      price: 7.0,
      category: "tea",
    },

    // COLD DRINKS
    {
      id: "mocha-frappe",
      name: "Mocha Frappe",
      price: 5.0,
      category: "cold-drinks",
    },
    {
      id: "caramel-frappe",
      name: "Caramel Frappe",
      price: 5.0,
      category: "cold-drinks",
    },
    {
      id: "salted-caramel-frappe",
      name: "Salted Caramel Frappe",
      price: 5.0,
      category: "cold-drinks",
    },
    {
      id: "vanilla-frappe",
      name: "Vanilla Frappe",
      price: 4.5,
      category: "cold-drinks",
    },
    {
      id: "white-mocha-frappe",
      name: "White Mocha Frappe",
      price: 5.0,
      category: "cold-drinks",
    },
    {
      id: "toffee-nut-frappe",
      name: "Toffee Nut Frappe",
      price: 5.0,
      category: "cold-drinks",
    },
    {
      id: "iced-latte",
      name: "Iced Latte",
      price: 4.0,
      category: "cold-drinks",
    },
    {
      id: "iced-mocha",
      name: "Iced Mocha",
      price: 4.0,
      category: "cold-drinks",
    },
    {
      id: "iced-spanish-latte",
      name: "Iced Spanish Latte",
      price: 4.5,
      category: "cold-drinks",
    },
    {
      id: "iced-white-mocha",
      name: "Iced White Mocha",
      price: 4.5,
      category: "cold-drinks",
    },
    {
      id: "iced-matcha",
      name: "Iced Matcha",
      price: 5.5,
      category: "cold-drinks",
    },
    {
      id: "strawberry-matcha",
      name: "Strawberry Matcha",
      price: 5.5,
      category: "cold-drinks",
    },
    {
      id: "redbull",
      name: "Redbull",
      price: 6.0,
      category: "cold-drinks",
    },

    // ADD-ON
    { id: "addon-flavor", name: "Flavor", price: 0.5, category: "add-on" },
    {
      id: "addon-skimmed-milk",
      name: "Skimmed Milk",
      price: 0.5,
      category: "add-on",
    },
    {
      id: "addon-lactose-free-milk",
      name: "Lactose Free Milk",
      price: 1.0,
      category: "add-on",
    },
    { id: "addon-oat-milk", name: "Oat Milk", price: 1.0, category: "add-on" },
    {
      id: "addon-almond-milk",
      name: "Almond Milk",
      price: 1.0,
      category: "add-on",
    },
    {
      id: "addon-coconut-milk",
      name: "Coconut Milk",
      price: 1.0,
      category: "add-on",
    },
    { id: "addon-sauce", name: "Sauce", price: 0.5, category: "add-on" },

    // SHAKES
    { id: "oreo-shake", name: "Oreo Shake", price: 5.0, category: "shakes" },
    { id: "lotus-shake", name: "Lotus Shake", price: 5.0, category: "shakes" },
    {
      id: "strawberry-shake",
      name: "Strawberry Shake",
      price: 5.0,
      category: "shakes",
    },
    {
      id: "chocolate-shake",
      name: "Chocolate Shake",
      price: 5.0,
      category: "shakes",
    },
    {
      id: "frozen-yogurt-shake",
      name: "Frozen Yogurt Shake",
      price: 6.0,
      category: "shakes",
    },
    {
      id: "blueberry-bloom-shake",
      name: "Blueberry Bloom Shake",
      price: 5.0,
      category: "shakes",
    },
    {
      id: "ashta-delight-shake",
      name: "Ashta Delight Shake",
      price: 6.0,
      category: "shakes",
    },

    // REFRESHERS
    {
      id: "mojito-refresher",
      name: "Mojito",
      price: 5.0,
      category: "refreshers",
    },
    {
      id: "passion-fruit-refresher",
      name: "Passion Fruit",
      price: 5.0,
      category: "refreshers",
    },
    {
      id: "four-berries",
      name: "Four Berries",
      price: 5.0,
      category: "refreshers",
    },
    {
      id: "homemade-ice-tea-peach",
      name: "Homemade Ice Tea Peach",
      price: 5.0,
      category: "refreshers",
    },
    {
      id: "purple-lychee",
      name: "Purple Lychee",
      price: 5.0,
      category: "refreshers",
    },
    {
      id: "sparkling-water",
      name: "Sparkling Water",
      price: 2.0,
      category: "refreshers",
    },
    { id: "water", name: "Water (0.5 ml)", price: 1.0, category: "refreshers" },

    // FRUIT SMOOTHIES
    {
      id: "mango-smoothie",
      name: "Mango",
      price: 5.0,
      category: "fruit-smoothies",
    },
    {
      id: "strawberry-smoothie",
      name: "Strawberry",
      price: 5.0,
      category: "fruit-smoothies",
    },
    {
      id: "mixed-berries-smoothie",
      name: "Mixed Berries",
      price: 5.0,
      category: "fruit-smoothies",
    },
    {
      id: "tropical-fruits-smoothie",
      name: "Tropical Fruits",
      price: 5.0,
      category: "fruit-smoothies",
    },
    {
      id: "apple-kiwi-smoothie",
      name: "Apple Kiwi",
      price: 5.0,
      category: "fruit-smoothies",
    },

    // SPIRITS (GLASS)
    {
      id: "gin-basil",
      name: "Gin Basil",
      price: 5.0,
      category: "spirits-glass",
    },
    {
      id: "passion-fruit-martini",
      name: "Passion Fruit Martini",
      price: 6.0,
      category: "spirits-glass",
    },
    {
      id: "lychee-martini",
      name: "Lychee Martini",
      price: 6.0,
      category: "spirits-glass",
    },
    {
      id: "espresso-martini",
      name: "Espresso Martini",
      price: 6.0,
      category: "spirits-glass",
    },
    {
      id: "strawberry-daiquiri",
      name: "Strawberry Daiquiri",
      price: 6.0,
      category: "spirits-glass",
    },
    {
      id: "margarita",
      name: "Margarita",
      price: 5.0,
      category: "spirits-glass",
    },
    { id: "negroni", name: "Negroni", price: 6.0, category: "spirits-glass" },
    {
      id: "cosmopolitan",
      name: "Cosmopolitan",
      price: 6.0,
      category: "spirits-glass",
    },
    {
      id: "mojito-spirit",
      name: "Mojito",
      price: 5.0,
      category: "spirits-glass",
    },
    {
      id: "whiskey-sour",
      name: "Whiskey Sour",
      price: 6.0,
      category: "spirits-glass",
    },
    {
      id: "pina-colada",
      name: "Pina Colada",
      price: 6.0,
      category: "spirits-glass",
    },
    { id: "red-wine", name: "Red Wine", price: 5.0, category: "spirits-glass" },
    {
      id: "ixsir-altitudes-rose-wine",
      name: "Ixsir Altitudes Rosé Wine",
      price: 7.0,
      category: "spirits-glass",
    },
    {
      id: "white-wine",
      name: "White Wine",
      price: 6.0,
      category: "spirits-glass",
    },
    {
      id: "almaza-beer",
      name: "Almaza Beer",
      price: 3.5,
      category: "spirits-glass",
    },
    {
      id: "almaza-light",
      name: "Almaza Light",
      price: 4.0,
      category: "spirits-glass",
    },
    {
      id: "heineken-beer",
      name: "Heineken Beer",
      price: 5.0,
      category: "spirits-glass",
    },
    {
      id: "prosecco-glass",
      name: "Prosecco",
      price: 5.0,
      category: "spirits-glass",
    },
    {
      id: "jw-black-label",
      name: "JW Black Label",
      price: 7.0,
      category: "spirits-glass",
    },
    {
      id: "chivas-glass",
      name: "Chivas",
      price: 8.0,
      category: "spirits-glass",
    },
    {
      id: "grey-goose",
      name: "Grey Goose",
      price: 8.0,
      category: "spirits-glass",
    },
    {
      id: "stolichnaya-red-vodka",
      name: "Stolichnaya Red Vodka",
      price: 7.0,
      category: "spirits-glass",
    },

    // SPIRITS (BOTTLES)
    {
      id: "jw-red-label-bottle",
      name: "JW Red Label",
      price: 50.0,
      category: "spirits-bottles",
    },
    {
      id: "jw-black-label-bottle",
      name: "JW Black Label",
      price: 70.0,
      category: "spirits-bottles",
    },
    {
      id: "jameson-irish-whiskey",
      name: "Jameson Irish Whiskey",
      price: 50.0,
      category: "spirits-bottles",
    },
    {
      id: "chivas-12y",
      name: "Chivas 12Y",
      price: 50.0,
      category: "spirits-bottles",
    },
    {
      id: "chivas-regal",
      name: "Chivas Regal",
      price: 70.0,
      category: "spirits-bottles",
    },
    {
      id: "stolichnaya-red-bottle",
      name: "Stolichnaya Red",
      price: 40.0,
      category: "spirits-bottles",
    },
    {
      id: "grey-goose-bottle",
      name: "Grey Goose",
      price: 80.0,
      category: "spirits-bottles",
    },
    {
      id: "gordons-gin",
      name: "Gordon's Gin",
      price: 30.0,
      category: "spirits-bottles",
    },
    {
      id: "hendricks-gin",
      name: "Hendricks Gin",
      price: 100.0,
      category: "spirits-bottles",
    },
    {
      id: "tanqueray-gin",
      name: "Tanqueray Gin",
      price: 100.0,
      category: "spirits-bottles",
    },
    {
      id: "ksara-reserve-du-couvent",
      name: "Ksara Reserve du Couvent",
      price: 25.0,
      category: "spirits-bottles",
    },
    {
      id: "ksara-sunset-rose",
      name: "Ksara Sunset Rosé",
      price: 25.0,
      category: "spirits-bottles",
    },
    {
      id: "ksara-blanc-de-blanc",
      name: "Ksara Blanc de Blanc",
      price: 25.0,
      category: "spirits-bottles",
    },
    {
      id: "ixsir-altitudes-red-wine",
      name: "Ixsir Altitudes Red Wine",
      price: 35.0,
      category: "spirits-bottles",
    },
    {
      id: "ixsir-altitudes-rose-wine-bottle",
      name: "Ixsir Altitudes Rosé Wine",
      price: 35.0,
      category: "spirits-bottles",
    },
    {
      id: "ixsir-altitudes-white-wine",
      name: "Ixsir Altitudes White Wine",
      price: 35.0,
      category: "spirits-bottles",
    },
    {
      id: "casa-bottega-prosecco",
      name: "Casa Bottega Prosecco",
      price: 35.0,
      category: "spirits-bottles",
    },

    // FRESH JUICES
    {
      id: "fresh-orange",
      name: "Fresh Orange",
      price: 3.0,
      category: "fresh-juices",
    },
    {
      id: "fresh-lemonade",
      name: "Fresh Lemonade",
      price: 3.0,
      category: "fresh-juices",
    },
    {
      id: "minted-lemonade",
      name: "Minted Lemonade",
      price: 4.0,
      category: "fresh-juices",
    },

    // CROISSANTS
    {
      id: "croissant-cheese",
      name: "Cheese",
      price: 4.0,
      category: "croissants",
      ingredients: "Croissant",
    },
    {
      id: "croissant-zaatar",
      name: "Zaatar",
      price: 3.0,
      category: "croissants",
      ingredients: "Croissant",
    },
    {
      id: "croissant-chocolate",
      name: "Chocolate",
      price: 4.0,
      category: "croissants",
      ingredients: "Croissant",
    },
    {
      id: "croissant-almond",
      name: "Almond",
      price: 4.0,
      category: "croissants",
      ingredients: "Croissant",
    },
    {
      id: "croissant-almond-chocolate",
      name: "Almond Chocolate",
      price: 5.0,
      category: "croissants",
      ingredients: "Croissant",
    },
    {
      id: "croissant-triple-chocolate",
      name: "Triple Chocolate",
      price: 4.0,
      category: "croissants",
      ingredients: "Croissant",
    },
    {
      id: "croissant-turkey-cheese",
      name: "Turkey & Cheese",
      price: 5.0,
      category: "croissants",
      ingredients: "Croissant",
    },
    {
      id: "croissant-cinnamon",
      name: "Cinnamon",
      price: 5.0,
      category: "croissants",
      ingredients: "Croissant",
    },

    // DESSERTS
    {
      id: "tropezienne",
      name: "Tropezienne",
      price: 5.0,
      category: "desserts",
    },
    {
      id: "profiterol-creamy",
      name: "Profiterol Creamy",
      price: 5.0,
      category: "desserts",
    },
    {
      id: "paris-brest",
      name: "Paris Brest",
      price: 5.0,
      category: "desserts",
    },
    {
      id: "baba-oh-rhum",
      name: "Baba Oh Rhum",
      price: 5.0,
      category: "desserts",
    },
    {
      id: "eclair-strawberry",
      name: "Eclair (Strawberry)",
      price: 5.0,
      category: "desserts",
    },
    {
      id: "eclair-lotus",
      name: "Eclair (Lotus)",
      price: 5.0,
      category: "desserts",
    },
    {
      id: "eclair-caramel",
      name: "Eclair (Caramel)",
      price: 5.0,
      category: "desserts",
    },
    {
      id: "eclair-chocolate",
      name: "Eclair (Chocolate)",
      price: 5.0,
      category: "desserts",
    },
    {
      id: "eclair-royale",
      name: "Eclair Royale",
      price: 5.0,
      category: "desserts",
    },
    {
      id: "tart-mango",
      name: "Tart (Mango)",
      price: 5.0,
      category: "desserts",
    },
    {
      id: "tart-strawberry",
      name: "Tart (Strawberry)",
      price: 5.0,
      category: "desserts",
    },
    {
      id: "tart-blueberry",
      name: "Tart (Blueberry)",
      price: 5.0,
      category: "desserts",
    },
    {
      id: "tart-choc-orange",
      name: "Tart (Choc Orange)",
      price: 5.0,
      category: "desserts",
    },
    {
      id: "tart-chocolate",
      name: "Tart (Chocolate)",
      price: 5.0,
      category: "desserts",
    },
    {
      id: "tart-creme-brulee",
      name: "Tart (Crème Brûlée)",
      price: 5.0,
      category: "desserts",
    },
    {
      id: "mille-feuille",
      name: "Mille Feuille",
      price: 5.0,
      category: "desserts",
    },
    {
      id: "berry-fusion",
      name: "Berry Fusion",
      price: 6.0,
      category: "desserts",
    },
    { id: "raphaello", name: "Raphaello", price: 6.0, category: "desserts" },
    {
      id: "white-choc-blueberry",
      name: "White Choc Blueberry",
      price: 5.0,
      category: "desserts",
    },
    {
      id: "big-tart-mango",
      name: "Big Tart Mango",
      price: 6.0,
      category: "desserts",
    },
    {
      id: "big-tart-strawberry",
      name: "Big Tart Strawberry",
      price: 6.0,
      category: "desserts",
    },
    { id: "muffins", name: "Muffins", price: 4.0, category: "desserts" },
    { id: "cookies", name: "Cookies", price: 3.0, category: "desserts" },
    {
      id: "cookies-lotus",
      name: "Cookies Lotus",
      price: 5.0,
      category: "desserts",
    },
    {
      id: "cookies-oreo",
      name: "Cookies Oreo",
      price: 5.0,
      category: "desserts",
    },
    {
      id: "cookies-kinder",
      name: "Cookies Kinder",
      price: 5.0,
      category: "desserts",
    },
    {
      id: "bahamas-cake",
      name: "Bahamas Cake",
      price: 5.0,
      category: "desserts",
    },
    {
      id: "fudge-cake",
      name: "Fudge Cake",
      price: 5.0,
      category: "desserts",
    },
    {
      id: "biscuit-au-chocolat",
      name: "Biscuit au Chocolat",
      price: 5.0,
      category: "desserts",
    },
    {
      id: "trio-chocolate",
      name: "Trio Chocolate",
      price: 5.0,
      category: "desserts",
    },
    {
      id: "strawberry-cheesecake",
      name: "Strawberry Cheesecake",
      price: 6.0,
      category: "desserts",
    },
    {
      id: "oreo-cheesecake",
      name: "Oreo Cheesecake",
      price: 6.0,
      category: "desserts",
    },
    {
      id: "blueberry-cheesecake",
      name: "Blueberry Cheesecake",
      price: 6.0,
      category: "desserts",
    },
    {
      id: "apple-pie",
      name: "Apple Pie",
      price: 6.0,
      category: "desserts",
    },
    {
      id: "tiramissu-can",
      name: "Tiramissu Can",
      price: 7.0,
      category: "desserts",
    },
    { id: "meghle", name: "Meghle", price: 7.0, category: "desserts" },
  ],
};

// Restaurant Menu Data
const restoMenuData = {
  categories: [
    { id: "breakfast", name: "Breakfast", image: "../assets/breakfast.jpeg" },
    { id: "starters", name: "Starters", image: "../assets/starters.jpeg" },
    { id: "salads", name: "Salads", image: "../assets/salads.jpeg" },
    { id: "pizza", name: "Pizza", image: "../assets/pizza.jpeg" },
    { id: "pasta", name: "Pasta", image: "../assets/pasta.jpeg" },
    {
      id: "sandwiches-burgers",
      name: "Sandwiches & Burgers",
      image: "../assets/sandwiches-and-burgers.jpeg",
    },
    { id: "main-dish", name: "Main Dish", image: "../assets/main-dish.jpeg" },
    { id: "add-on-resto", name: "Add-On" },
    { id: "shisha", name: "Shisha", image: "../assets/shisha.jpeg" },
    {
      id: "drinks-desserts",
      name: "Drinks & Desserts",
      image: "../assets/drinks-and-desserts.jpeg",
    },
    {
      id: "lent-appetisers",
      name: "Lent Appetisers",
      image: "../assets/lent-appetisers.png",
      fullRow: true,
    },
    {
      id: "lent-main-dishes",
      name: "Lent Main Dishes",
      image: "../assets/lent-menu.png",
      fullRow: true,
    },
  ],
  items: [
    // BREAKFAST
    {
      id: "dreamy-greek-yogurt",
      name: "Dreamy Greek Yogurt & Granola",
      price: 8.0,
      category: "breakfast",
      ingredients: "Seasonal fruits & honey",
      image: "../assets/dreamy-greek-yogurt.jpeg",
    },
    {
      id: "halloumi-pesto",
      name: "Halloumi Pesto Excellence",
      price: 8.0,
      category: "breakfast",
      ingredients: "Ciabatta bread with cucumber & tomato",
      image: "../assets/halloumi-pesto.jpeg",
    },
    {
      id: "goat-cheese-bruschetta",
      name: "Goat Cheese Bruschetta",
      price: 8.0,
      category: "breakfast",
      ingredients: "Rocca, red apple, walnuts & balsamic",
      image: "../assets/goat-cheese-bruschetta.jpeg",
    },
    {
      id: "eggs-your-style",
      name: "Eggs Your Style",
      price: 5.0,
      category: "breakfast",
      ingredients: "Scrambled, sunny side up, omelet, or boiled",
    },
    {
      id: "fluffy-pancakes",
      name: "Fluffy Pancakes",
      price: 10.0,
      category: "breakfast",
      ingredients:
        "Chocolate syrup, banana, strawberry, whipped cream, maple syrup",
      image: "../assets/fluffy-pancakes.jpeg",
    },
    {
      id: "steak-eggs",
      name: "Mouth-watering Steak & Eggs",
      price: 12.0,
      category: "breakfast",
      ingredients: "Juicy seared steak with perfectly cooked eggs",
      image: "../assets/steak-eggs.jpeg",
    },
    {
      id: "croissant-zaatar-resto",
      name: "Croissant (Zaatar)",
      price: 3.0,
      category: "breakfast",
      image: "../assets/croissant-zaatar.jpeg",
    },
    {
      id: "croissant-cheese-resto",
      name: "Croissant (Cheese)",
      price: 4.0,
      category: "breakfast",
      image: "../assets/croissant-cheese.jpeg",
    },
    {
      id: "croissant-almond-resto",
      name: "Croissant (Almond)",
      price: 4.0,
      category: "breakfast",
    },
    {
      id: "croissant-almond-chocolate-resto",
      name: "Croissant (Almond Chocolate)",
      price: 5.0,
      category: "breakfast",
    },
    {
      id: "croissant-turkey-cheese-resto",
      name: "Croissant (Turkey & Cheese)",
      price: 5.0,
      category: "breakfast",
    },
    {
      id: "croissant-triple-chocolate-resto",
      name: "Croissant (Triple Chocolate)",
      price: 4.0,
      category: "breakfast",
      image: "../assets/croissant-triple-chocolate.jpeg",
    },

    // STARTERS
    {
      id: "blazing-dynamite-shrimps",
      name: "Blazing Dynamite Shrimps",
      price: 13.0,
      category: "starters",
      ingredients: "Breaded shrimps tossed in house dynamite sauce",
      image: "../assets/blazing-dynamite-shrimps.jpeg",
    },
    {
      id: "avocado-on-toast",
      name: "Avocado On Toast",
      price: 7.0,
      category: "starters",
      ingredients: "Avocado mix, cherry tomato & parmesan",
      image: "../assets/avocado-on-toast.jpeg",
    },
    {
      id: "smoked-salmon-carpaccio",
      name: "Smoked Salmon Carpaccio",
      price: 18.0,
      category: "starters",
      ingredients: "Dill, capers, lemon, olive oil & toast",
      image: "../assets/smoked-salmon-carpaccio.jpeg",
    },
    {
      id: "mozzarella-sticks",
      name: "Mozzarella Sticks",
      price: 8.0,
      category: "starters",
      ingredients: "Breaded mozzarella sticks with marinara sauce",
      image: "../assets/mozzarella-sticks.jpeg",
    },
    {
      id: "truffle-fries-resto",
      name: "Truffle Fries",
      price: 8.0,
      category: "starters",
      image: "../assets/truffle-fries-resto.jpeg",
    },
    {
      id: "golden-fries",
      name: "Golden Fries",
      price: 5.0,
      category: "starters",
      image: "../assets/golden-fries.jpeg",
    },
    {
      id: "edamame",
      name: "Edamame",
      price: 7.0,
      category: "starters",
      image: "../assets/edamame.jpeg",
    },
    {
      id: "tenders",
      name: "Tenders",
      price: 8.0,
      category: "starters",
      ingredients: "4 pcs with cup honey mustard sauce",
      image: "../assets/tenders.jpeg",
    },
    {
      id: "dumplings-shrimps",
      name: "Dumplings Shrimps",
      price: 14.5,
      category: "starters",
      image: "../assets/dumplings-shrimps.jpeg",
    },

    // SALADS
    {
      id: "goat-cheese-salad",
      name: "Goat Cheese Salad",
      price: 15.0,
      category: "salads",
      ingredients:
        "Greens, spinach, red apple, walnuts, dry figs, cherry tomato & balsamic",
      image: "../assets/goat-cheese-salad.jpeg",
    },
    {
      id: "quinoa-bowl",
      name: "Quinoa Bowl",
      price: 14.0,
      category: "salads",
      ingredients:
        "Mixed greens, cherry tomato, dry figs, cranberry, almonds & citrus dressing",
      image: "../assets/quinoa-bowl.jpeg",
    },
    {
      id: "caesar-royal-chicken",
      name: "Caesar Royal (Add Chicken)",
      price: 14.0,
      category: "salads",
      ingredients: "Lettuce, croutons, parmesan & house Caesar sauce + Chicken",
      image: "../assets/caesar-royal-chicken.jpeg",
    },
    {
      id: "shrimp-salad",
      name: "Shrimp Salad",
      price: 16.0,
      category: "salads",
      ingredients:
        "Mixed greens, quinoa, cherry tomato, Indian onion, avocado & herbal dressing",
      image: "../assets/shrimp-salad.jpeg",
    },
    {
      id: "fusion-crab-salad",
      name: "Fusion Crab Salad",
      price: 14.0,
      category: "salads",
      ingredients: "Carrot, cucumber, strawberry, cabbage & Asian dressing",
      image: "../assets/fusion-crab-salad.jpeg",
    },

    // PIZZA
    {
      id: "margherita-resto",
      name: "Margherita",
      price: 10.0,
      category: "pizza",
      ingredients: "Tomato sauce, mozzarella & basil",
      image: "../assets/margherita.jpeg",
    },
    {
      id: "vegetariana",
      name: "Vegetariana",
      price: 12.0,
      category: "pizza",
      ingredients:
        "Zucchini, eggplant, bell peppers, mushroom, tomato sauce & mozzarella",
      image: "../assets/Vegetariana.jpeg",
    },
    {
      id: "quattro-formaggi",
      name: "Quattro Formaggi",
      price: 13.0,
      category: "pizza",
      ingredients: "Mozzarella, gorgonzola, parmesan & formaggio duro",
      image: "../assets/quattro-fromaggi.jpeg",
    },
    {
      id: "diavola-resto",
      name: "Diavola",
      price: 14.0,
      category: "pizza",
      ingredients: "Tomato sauce, salami picante & mozzarella",
      image: "../assets/diavola.jpeg",
    },

    // SANDWICHES & BURGERS
    {
      id: "reis-club-sandwich",
      name: "Rei's Club Sandwich",
      price: 12.0,
      category: "sandwiches-burgers",
      ingredients:
        "Smoked turkey, turkey bacon, emmental, lettuce, tomato, pickles, avocado, mayo & Dijon",
      image: "../assets/reis-club-sandwich.jpeg",
    },
    {
      id: "mighty-steak-sandwich",
      name: "Mighty Steak Sandwich",
      price: 13.0,
      category: "sandwiches-burgers",
      ingredients:
        "Beef tenderloin, sourdough, onions, bell peppers, emmental & steak sauce",
      image: "../assets/mighty-steak-sandwich.jpeg",
    },
    {
      id: "chicken-avo-wrap",
      name: "The Chicken Avo Wrap",
      price: 10.0,
      category: "sandwiches-burgers",
      ingredients:
        "Grilled chicken breast, avocado mix, pickles, lettuce & honey mustard",
      image: "../assets/chicken-avo-wrap.jpeg",
    },
    {
      id: "reis-prime-burger",
      name: "Rei's Prime Burger",
      price: 12.0,
      category: "sandwiches-burgers",
      ingredients:
        "Angus beef, cheddar cheese, lettuce, pickles, onion, tomato & house burger sauce",
      image: "../assets/reis-prime-burger.jpeg",
    },
    {
      id: "mushroom-burger",
      name: "Mushroom Burger",
      price: 13.0,
      category: "sandwiches-burgers",
      ingredients: "Gravy mushroom sauce, Beef patty, Emmental cheese, Buns",
      image: "../assets/mushroom-burger.jpeg",
    },
    {
      id: "truffle-burger",
      name: "Truffle Burger",
      price: 14.0,
      category: "sandwiches-burgers",
      ingredients: "Truffle mayo sauce, Mushrooms, Beef patty, Buns",
      image: "../assets/truffle-burger.jpeg",
    },
    {
      id: "golden-crispy-burger",
      name: "Golden Crispy Burger",
      price: 12.0,
      category: "sandwiches-burgers",
      ingredients:
        "Honey mustard sauce, Chicken crispy, Cheddar slice, Pickles",
      image: "../assets/golden-crispy-burger.jpeg",
    },

    // MAIN DISH
    {
      id: "steak-fries",
      name: "Steak & Fries",
      price: 19.0,
      category: "main-dish",
      ingredients: "Mushroom or pepper sauce",
      image: "../assets/steak-fries.jpeg",
    },
    {
      id: "creamy-chicken-mushroom",
      name: "Creamy Chicken Mushroom",
      price: 15.0,
      category: "main-dish",
      ingredients: "Grilled chicken breast, mushroom sauce & fries",
      image: "../assets/creamy-chicken-mushroom.jpeg",
    },
    {
      id: "grilled-jumbo-shrimps",
      name: "Grilled Jumbo Shrimps",
      price: 22.0,
      category: "main-dish",
      ingredients: "Marinated in unique flavors",
      image: "../assets/grilled-jumbo-shrimps.jpeg",
    },
    {
      id: "grilled-salmon-miso",
      name: "Grilled Salmon Miso",
      price: 23.0,
      category: "main-dish",
      ingredients: "With sautéed vegetables",
      image: "../assets/grilled-salmon-miso.jpeg",
    },
    {
      id: "addon-chicken",
      name: "Chicken",
      price: 4.0,
      category: "add-on-resto",
    },
    {
      id: "addon-shrimp",
      name: "Shrimp",
      price: 4.0,
      category: "add-on-resto",
    },
    {
      id: "addon-smoked-salmon",
      name: "Smoked Salmon",
      price: 4.0,
      category: "add-on-resto",
    },
    {
      id: "linguini-alfredo",
      name: "Linguini Alfredo",
      price: 15.0,
      category: "pasta",
      image: "../assets/linguini-alfredo.jpeg",
    },
    {
      id: "penne-arrabbiata",
      name: "Penne Arrabbiata",
      price: 10.0,
      category: "pasta",
      image: "../assets/penne-arrabbiata.jpeg",
    },
    {
      id: "linguini-pesto",
      name: "Linguini Pesto",
      price: 13.0,
      category: "pasta",
      image: "../assets/linguini-pesto.jpeg",
    },
    {
      id: "truffle-pasta",
      name: "Truffle Pasta",
      price: 14.0,
      category: "pasta",
      ingredients: "Mushrooms, With truffle white sauce, Penne pasta",
      image: "../assets/truffle-pasta.jpeg",
    },
    {
      id: "shrimp-rose-pasta",
      name: "Shrimp Rose Pasta",
      price: 15.0,
      category: "pasta",
      ingredients: "Rose sauce, Penne pasta, Shrimps",
      image: "../assets/Shrimp-rose-pasta.jpeg",
    },

    // LENT APPETISERS
    {
      id: "eggplant-stuffed-baba-ghanouj",
      name: "Eggplant Stuffed with Baba Ghanouj Served with Tomato Sauce",
      price: 11.0,
      category: "lent-appetisers",
      image: "../assets/eggplant.jpeg",
    },
    {
      id: "truffle-hummus-falafel",
      name: "Truffle Hummus with Falafel",
      price: 9.0,
      category: "lent-appetisers",
    },
    {
      id: "falafel-hummus-chilly-oil",
      name: "Falafel Hummus with Chilly Oil",
      price: 7.0,
      category: "lent-appetisers",
      image: "../assets/hummus with falafel.jpeg",
    },
    {
      id: "cauliflower-smoked-chumichurri",
      name: "Cauliflower with Smoked Chumichurri",
      price: 11.0,
      category: "lent-appetisers",
      image: "../assets/cauliflower.jpeg",
    },

    // LENT MAIN DISHES
    {
      id: "peters-fish-stuffed-herbs",
      name: "Peter's Fish Stuffed with Herbs Served with Chumichuri and Tartar Sauce",
      price: 19.0,
      category: "lent-main-dishes",
      image: "../assets/peters fish.jpeg",
    },
    {
      id: "shrimp-orzo",
      name: "Shrimp Orzo",
      price: 17.0,
      category: "lent-main-dishes",
      image: "../assets/shrimp orzo.jpeg",
    },
    {
      id: "miso-salmon-red-tahini",
      name: "Miso Salmon with Red Tahini",
      price: 28.0,
      category: "lent-main-dishes",
      image: "../assets/miso salmon.jpeg",
    },
    {
      id: "avocado-salmon-tartar",
      name: "Avocado Salmon Tartar",
      price: 18.0,
      category: "lent-main-dishes",
      image: "../assets/avocado salmon tartar.jpeg",
    },
    {
      id: "fish-chips",
      name: "Fish & Chips",
      price: 12.0,
      category: "lent-main-dishes",
    },
    {
      id: "fish-burger",
      name: "Fish Burger",
      price: 9.0,
      category: "lent-main-dishes",
    },
    {
      id: "shrimp-provincial",
      name: "Shrimp Provincial",
      price: 13.0,
      category: "lent-main-dishes",
    },

    // SHISHA
    { id: "mouassal", name: "Mouassal", price: 7.0, category: "shisha" },
    {
      id: "mouassal-jabali",
      name: "Mouassal Jabali",
      price: 9.0,
      category: "shisha",
    },
  ],
};
